---
# tasks file for postgresqls

- name: Установка необходимых пакетов
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ packages_to_install }}" #Цикл будет перебирать все значения из переменной "packages"

- name: Установка необходимого модуля python psycopg2
  ansible.builtin.pip:
    name: psycopg2

- name: Установка Postgresql(Slave)
  apt:
    name: "postgresql"
    state: present
    update_cache: true

- name: Ожидание инициализации Postgresql
  ansible.builtin.wait_for:
    path: /etc/postgresql/14/main/pg_hba.conf # ожидает создания файла

- name: Настройка 1 Postgresql
  ansible.builtin.template:
    src: pg_hba.conf
    dest: /etc/postgresql/14/main/pg_hba.conf

- name: Настройка 2 Postgresql
  ansible.builtin.template:
    src: postgresql.conf
    dest: /etc/postgresql/14/main/postgresql.conf
  notify: "Postgres stop"

- name: Подготовка к копированию баз с основного сервера
  ansible.builtin.file:
    path: /var/lib/postgresql/14/main/
    state: absent

- name: Копирование файла pgpass
  ansible.builtin.copy:
    src: pasfile/.pgpass
    dest: /var/lib/postgresql/.pgpass
    owner: postgres # владелец
    group: postgres # группа
    mode: '0600'

- name: Копирование БД из main сервера
  ansible.builtin.command: pg_basebackup -h {{ ip_vm4 }} -D /var/lib/postgresql/14/main -U syncuser -w -v -R
  become_user: postgres
  notify: "Postgres start"

- name: Копирование скрипта дампа БД
  ansible.builtin.template:
    src: dumpdb_mediawiki.sh.j2
    dest: /var/lib/postgresql/dumpdb_mediawiki.sh
    owner: postgres
    group: postgres
    mode: '0700'

- name: Копирование скрипта востановления БД
  ansible.builtin.template:
    src: restoredb_mediawiki.sh.j2
    dest: /var/lib/postgresql/restoredb_mediawiki.sh
    owner: postgres
    group: "{{ sudo_user_name }}"
    mode: '0770'

- name: Создаём директорию для дампов БД
  ansible.builtin.file:
    path: /var/backups/db-backup
    state: directory
    owner: postgres
    group: "{{ sudo_user_name }}"
    mode: '0760'

- name: Создание задания cron (дамп бд) # каждый день в 04-00
  ansible.builtin.cron:
    name: backup_db_mediawiki
    minute: "15"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    user: postgres
    job: "/var/lib/postgresql/dumpdb_mediawiki.sh"

- name: Создаём директорию .ssh пользователя postgres
  ansible.builtin.file:
    path: /var/lib/postgresql/.ssh
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Добавляем публичный ключ для работы failover
  ansible.builtin.lineinfile:
    path: /var/lib/postgresql/.ssh/authorized_keys # в какой файл
    line: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMkxoXpokYG318CkfYy3CbagT0/2m1dyFZEhcN+30RafxHM57BNSgLgBeCBo1ePjrUrixMBSu+OfPprlY3o8O+o= postgres@vm
    create: yes # создаст если нет

- name: Копирование приватного ключа ssh
  copy:
    src: key/id_ed25519
    dest: /var/lib/postgresql/.ssh # куда
    remote_src: no
    mode: '0600' # права
    owner: postgres
    group: postgres
