---
# tasks file for pgpool

- name: Установка Pgpool2 #Имя задачи
  apt: #Используемый модуль
    name: "pgpool2" #Имя пакета из цикла
    state: present #Параметр действия. present - установить, absent - удалить
    update_cache: true # аналог apt update
  notify: "Pgpool stop"

- name: Настройка pcp.conf Pgpool2
  ansible.builtin.template:
    src: pcp.conf
    dest: /etc/pgpool2/pcp.conf

- name: Настройка pgpool.conf Pgpool2
  ansible.builtin.template:
    src: pgpool.conf
    dest: /etc/pgpool2/pgpool.conf

- name: Настройка pool_hba Pgpool2
  ansible.builtin.template:
    src: pool_hba.conf
    dest: /etc/pgpool2/pool_hba.conf

- name: Создаём скрипт failover для Pgpool2
  ansible.builtin.template:
    src: failover.sh
    dest: /etc/pgpool2/failover.sh
    mode: '0700'

- name: Настройка pool_passwd Pgpool2
  ansible.builtin.template:
    src: pool_passwd
    dest: /etc/pgpool2/pool_passwd
    owner: postgres
    group: postgres
    mode: '0600'
  notify: "Pgpool start"

- name: Создаём директорию .ssh пользователя postgres
  ansible.builtin.file:
    path: /var/lib/postgresql/.ssh
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Добавляем публичный ключ для работы failover
  ansible.builtin.lineinfile:
    path: /var/lib/postgresql/.ssh/authorized_keys # в какой файл
    line: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMkxoXpokYG318CkfYy3CbagT0/2m1dyFZEhcN+30RafxHM57BNSgLgBeCBo1ePjrUrixMBSu+OfPprlY3o8O+o= postgres@vm
    create: yes # создаст если нет

- name: Копирование приватного ключа ssh
  copy:
    src: key/id_ed25519
    dest: /var/lib/postgresql/.ssh # куда
    remote_src: no
    mode: '0600' # права
    owner: postgres
    group: postgres
