---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx_balancer: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm1: #Имя машины
          ansible_host: 158.160.34.47 #Адрес машины
    mediawiki: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm2: #Имя машины
          ansible_host: 192.168.10.12 #Адрес машины
          ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@158.160.34.47"' #подключение через vm1
        vm3: #Имя машины
          ansible_host: 192.168.10.13 #Адрес машины
          ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@158.160.34.47"' #подключение через vm1
    database_master: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm4: #Имя машины
          ansible_host: localhost #192.168.10.14 #Адрес машины
#          ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@158.160.34.47"' #подключение через vm1
    database_slave: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm5: #Имя машины
          ansible_host: 192.168.10.15 #Адрес машины
          ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@158.160.34.47"' #подключение через vm1
    Zabbix_server: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm6: #Имя машины
          ansible_host: 192.168.10.16 #Адрес машины
          ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@158.160.34.47"' #подключение через vm1
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: s10309758 #"ubuntu"
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    connection_protocol: ssh #тип подключения
    ansible_become: true
    ip_vm1: 192.168.10.11
    ip_vm2: 192.168.10.12
    ip_vm3: 192.168.10.13
    ip_vm4: 192.168.10.14
    ip_vm5: 192.168.10.15
    ip_vm6: 192.168.10.16
    hosts_deny: [vm6]
    instal_db: backup # clear or backup (for db mediawiki)
    url_adr: example-practicum.ru
    app_ver: mediawiki-1.42.3
