---
# tasks file for mediawiki

- name: Добавление {{ sudo_user_name }} в группу www-data
  ansible.builtin.user:
    name: "{{ sudo_user_name }}"
    groups: www-data
    append: true

- name: Скачивание архива с сайта mediawiki
  ansible.builtin.get_url:
    url: https://releases.wikimedia.org/mediawiki/1.42/{{ app_ver }}.tar.gz
    dest: ~/mediawiki.tar.gz

- name: Распаковка архива с приложением mediawiki
  ansible.builtin.unarchive:
    src: ~/mediawiki.tar.gz
    dest: /var/www
    owner: www-data
    group: www-data
    mode: '0660'
    remote_src: true

- name: Удаление архива
  ansible.builtin.file:
    state: absent
    path: ~/mediawiki.tar.gz

- name: Настройка mediawiki
  ansible.builtin.template:
    src: LocalSettings.php.j2
    dest: /var/www/{{ app_ver }}/LocalSettings.php
    owner: www-data
    group: www-data
    mode: '0600'
  when: instal_db == "backup"

- name: Добавляем публичный ключ для работы lsyncd
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys # в какой файл
    line: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMkxoXpokYG318CkfYy3CbagT0/2m1dyFZEhcN+30RafxHM57BNSgLgBeCBo1ePjrUrixMBSu+OfPprlY3o8O+o= root@vm
    create: yes # создаст если нет

- name: Копирование приватного ключа ssh
  copy:
    src: key/id_ed25519
    dest: /root/.ssh # куда
    remote_src: no
    mode: '0600' # права
    owner: root
    group: root

- name: Установка lsyncd #синхронизация файлов между серверами
  apt:
    name: "lsyncd"
    state: present
    update_cache: true

- name: Создаём директорию для файла настроек lsyncd
  ansible.builtin.file:
    path: /etc/lsyncd
    state: directory

- name: Настройка lsyncd
  ansible.builtin.template:
    src: lsyncd.conf.lua
    dest: /etc/lsyncd/lsyncd.conf.lua
  notify: "lsyncd Restart"

- name: Копирование скрипта дампа mediawiki
  ansible.builtin.template:
    src: dumpapp_mediawiki.sh.j2
    dest: /home/{{ sudo_user_name }}/dumpapp_mediawiki.sh
    owner: "{{ sudo_user_name }}"
    group: "{{ sudo_user_name }}"
    mode: '0700'

- name: Копирование скрипта востановления БД
  ansible.builtin.template:
    src: restoreapp_mediawiki.sh.j2
    dest: /home/{{ sudo_user_name }}/restoreapp_mediawiki.sh
    owner: "{{ sudo_user_name }}"
    group: "{{ sudo_user_name }}"
    mode: '0700'

- name: Создаём директорию для дампов БД
  ansible.builtin.file:
    path: /var/backups/app-backup
    state: directory
    owner: "{{ sudo_user_name }}"
    group: "{{ sudo_user_name }}"
    mode: '0760'

- name: Создание задания cron (дамп бд) # каждый день в 04-00
  ansible.builtin.cron:
    name: backupapp_mediawiki
    minute: "30"
    hour: "4"
    day: "*"
    month: "*"
    weekday: "*"
    user: "{{ sudo_user_name }}"
    job: "/home/{{ sudo_user_name }}/dumpapp_mediawiki.sh"
